AWSTemplateFormatVersion: "2010-09-09"
Description: A basic CloudFormation templates

Resources:
  devlmsappserver:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e53db6fd757e38c7
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "PORT=5000" > /home/ec2-user/.env
          chown ec2-user:ec2-user /home/ec2-user/.env
