AWSTemplateFormatVersion: "2010-09-09"
Description: A basic CloudFormation template

Resources:
  dev-lms-app-server:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e53db6fd757e38c7
      KeyName: testing
