name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Adjust region if needed

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file app-server/template.yaml \
            --stack-name dev-lms-app-server \
            --capabilities CAPABILITY_NAMED_IAM
            
      - name: Set environment variables
        run: echo "PORT=5000" >> $GITHUB_ENV  # Specify your port number here
